.TH "Blob" 3 "Mon Jun 11 2018" "Version Zelda 8-bit created by Brant B, Jacob K, and Matt L" "AP CS Final Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Blob
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEnemy\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBlob\fP (BufferedImage sprit, BufferedImage BG, String name, String grndType, Point location)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Blob\&.Blob (BufferedImage sprit, BufferedImage BG, String name, String grndType, Point location)"


.SH "Author"
.PP 
Generated automatically by Doxygen for AP CS Final Project from the source code\&.
