.TH "Chest" 3 "Mon Jun 11 2018" "Version Zelda 8-bit created by Brant B, Jacob K, and Matt L" "AP CS Final Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Chest
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTile\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChest\fP (ArrayList< \fBItems\fP > items)"
.br
.ti -1c
.RI "ArrayList< \fBItems\fP > \fBgetChestItems\fP ()"
.br
.ti -1c
.RI "void \fBsetChestItems\fP (int i, \fBItems\fP yeet)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Chest\&.Chest (ArrayList< \fBItems\fP > items)"

.SH "Member Function Documentation"
.PP 
.SS "ArrayList<\fBItems\fP> Chest\&.getChestItems ()"

.SS "void Chest\&.setChestItems (int i, \fBItems\fP yeet)"


.SH "Author"
.PP 
Generated automatically by Doxygen for AP CS Final Project from the source code\&.
