.TH "D:/Jacob/2017/Glastonbury High School Directory Reference" 3 "Mon Jun 11 2018" "Version Zelda 8-bit created by Brant B, Jacob K, and Matt L" "AP CS Final Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Jacob/2017/Glastonbury High School Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBGrade_10\fP"
.br
.in -1c
