.TH "deprecated" 3 "Mon Jun 11 2018" "Version Zelda 8-bit created by Brant B, Jacob K, and Matt L" "AP CS Final Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecated \- Deprecated List 

.IP "\fBMember \fBCharacter\&.Character\fP (BufferedImage img)\fP" 1c
.IP "\fBMember \fBIO\&.printMap\fP (char[][] arr)\fP" 1c
.IP "\fBMember \fBTile\&.Tile\fP (BufferedImage img)\fP" 1c
.PP

