.TH "GameInfo" 3 "Mon Jun 11 2018" "Version Zelda 8-bit created by Brant B, Jacob K, and Matt L" "AP CS Final Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameInfo
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBButtonListener\fP"
.br
.ti -1c
.RI "class \fBKeyReader\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static JPanel \fBgeneratePanel\fP (\fBMainCharacter\fP c, JPanel mapPanel)"
.br
.ti -1c
.RI "static void \fBupdateHealth\fP (int newHealth)"
.br
.ti -1c
.RI "static void \fBupdateAttack\fP (int newAttack)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static JPanel GameInfo\&.generatePanel (\fBMainCharacter\fP c, JPanel mapPanel)\fC [static]\fP"
Create a JPanel with all the buttons and info
.PP
\fBParameters:\fP
.RS 4
\fIc\fP (\fBMainCharacter\fP) 
.br
\fImapPanel\fP (??) 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "static void GameInfo\&.updateAttack (int newAttack)\fC [static]\fP"
Update player's attack indicator in \fBGameInfo\fP panel
.PP
\fBParameters:\fP
.RS 4
\fInewAttack\fP 
.RE
.PP

.SS "static void GameInfo\&.updateHealth (int newHealth)\fC [static]\fP"
Update player's health indicator in \fBGameInfo\fP panel
.PP
\fBParameters:\fP
.RS 4
\fInewHealth\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for AP CS Final Project from the source code\&.
