.TH "Items" 3 "Mon Jun 11 2018" "Version Zelda 8-bit created by Brant B, Jacob K, and Matt L" "AP CS Final Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Items
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBItems\fP (BufferedImage img)"
.br
.ti -1c
.RI "int \fBgetHealth\fP ()"
.br
.ti -1c
.RI "void \fBincreaseHealth\fP (int health)"
.br
.ti -1c
.RI "int \fBgetAttack\fP ()"
.br
.ti -1c
.RI "void \fBincreaseAttack\fP (int attack)"
.br
.ti -1c
.RI "int \fBgetDefense\fP ()"
.br
.ti -1c
.RI "void \fBincreaseDefense\fP (int defense)"
.br
.ti -1c
.RI "String \fBgetName\fP ()"
.br
.ti -1c
.RI "void \fBsetName\fP (String nme)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Items\&.Items (BufferedImage img)"

.SH "Member Function Documentation"
.PP 
.SS "int Items\&.getAttack ()"

.SS "int Items\&.getDefense ()"

.SS "int Items\&.getHealth ()"

.SS "String Items\&.getName ()"

.SS "void Items\&.increaseAttack (int attack)"

.SS "void Items\&.increaseDefense (int defense)"

.SS "void Items\&.increaseHealth (int health)"

.SS "void Items\&.setName (String nme)"


.SH "Author"
.PP 
Generated automatically by Doxygen for AP CS Final Project from the source code\&.
