.TH "MainCharacter" 3 "Mon Jun 11 2018" "Version Zelda 8-bit created by Brant B, Jacob K, and Matt L" "AP CS Final Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MainCharacter
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCharacter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMainCharacter\fP (BufferedImage img)"
.br
.ti -1c
.RI "\fBMainCharacter\fP (BufferedImage img, BufferedImage BG, String name, String type, Point \fBp\fP)"
.br
.ti -1c
.RI "\fBItems\fP \fBgetItem\fP (int index)"
.br
.ti -1c
.RI "void \fBsetItem\fP (\fBItems\fP input, int index)"
.br
.ti -1c
.RI "\fBItems\fP [] \fBgetBackpack\fP ()"
.br
.ti -1c
.RI "int \fBitemSpace\fP ()"
.br
.ti -1c
.RI "void \fBreadItems\fP ()"
.br
.ti -1c
.RI "int \fBgetMoney\fP ()"
.br
.ti -1c
.RI "void \fBaddMoney\fP (int add)"
.br
.ti -1c
.RI "void \fBattack\fP (\fBFloor\fP f)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MainCharacter\&.MainCharacter (BufferedImage img)"

.SS "MainCharacter\&.MainCharacter (BufferedImage img, BufferedImage BG, String name, String type, Point p)"

.SH "Member Function Documentation"
.PP 
.SS "void MainCharacter\&.addMoney (int add)"

.SS "void MainCharacter\&.attack (\fBFloor\fP f)"

.SS "\fBItems\fP [] MainCharacter\&.getBackpack ()"

.SS "\fBItems\fP MainCharacter\&.getItem (int index)"

.SS "int MainCharacter\&.getMoney ()"

.SS "int MainCharacter\&.itemSpace ()"

.SS "void MainCharacter\&.readItems ()"

.SS "void MainCharacter\&.setItem (\fBItems\fP input, int index)"


.SH "Author"
.PP 
Generated automatically by Doxygen for AP CS Final Project from the source code\&.
